# Generated by Django 3.2.6 on 2021-11-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('user_event_key', models.TextField(primary_key=True, serialize=False)),
                ('event_id', models.TextField(blank=True, null=True)),
                ('event_name', models.TextField(blank=True, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_start_dt', models.DateTimeField(blank=True, null=True)),
                ('event_end_dt', models.DateTimeField(blank=True, null=True)),
                ('event_attendee', models.TextField(blank=True, null=True)),
                ('event_attendee_email', models.TextField(blank=True, null=True)),
                ('event_location', models.TextField(blank=True, null=True)),
                ('event_start_dt_prev', models.DateTimeField(blank=True, null=True)),
                ('event_end_dt_prev', models.DateTimeField(blank=True, null=True)),
                ('event_attendee_prev', models.TextField(blank=True, null=True)),
                ('event_location_prev', models.TextField(blank=True, null=True)),
                ('delete_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('new_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('change_location_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('change_start_dt_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('change_end_dt_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('change_attendee_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('location_missing_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('inperson_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('zoom_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('msteams_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('gmeet_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('lunch_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('dinner_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('oneonone_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('external_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('internal_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('all_day_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('event_link', models.TextField(blank=True, null=True)),
                ('event_call_link', models.TextField(blank=True, null=True)),
                ('num_attendees', models.IntegerField(default=0)),
                ('organizer_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('creator_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('calendar_id', models.CharField(max_length=255)),
                ('calendar_name', models.CharField(max_length=255)),
                ('select_flg', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='calendarlist',
            index=models.Index(fields=['id', 'username', 'select_flg'], name='findslot_ca_id_c51159_idx'),
        ),
        migrations.AddField(
            model_name='calendarevents',
            name='calendar_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findslot.calendarlist'),
        ),
        migrations.AddIndex(
            model_name='calendarevents',
            index=models.Index(fields=['calendar_info', 'user_event_key'], name='findslot_ca_calenda_817c11_idx'),
        ),
    ]
